# Gets python to work right on bash
alias python='winpty python.exe'

alias gr='cd $GIT_REPOS'

# cmake using g++
alias gcmake="cmake -S . -B build -G 'MinGW Makefiles'"

# Prefer ls to show in a long list format
alias ls="ls -1 --color=auto"

# Custom Git Configs
git config --global pretty.date-oneline 'format:%C(auto)%h | %as | %s'

vimnotes() {
    cd $NOTES_DIR
    vim
}

vimsandbox() {
    cd ~/.vim/pack/sandbox/start/sandbox/plugin
    vim sandbox.vim
}

for f in $MILAM_NOTES_REPO_DIR/environment-config/bash/bash-procedures/*; do source $f; done
