set-option -g status-style bg='#1e1e2e',fg='#cdd6f4'
set -g status-right "#[fg=#cdd6f4,bg=#585b70] (#H) "
set -g status-left "#[fg=#cdd6f4,bg=#585b70][#S]#[bg=#1e1e2e] "
set -g window-status-format "#[fg=#11111b,bg=#9399b2] #I:#[fg=#cdd6f4,bg=#585b70] #W "
set -g window-status-current-format "#[fg=#11111b,bg=#cba6f7] #I:#[fg=#cdd6f4,bg=#585b70] #W "   
